/* Builds a standalone ACE Arsenal script for a mission directory. */
params [["_rawPreset", [], [[]]]];

([_rawPreset] call RACA_fnc_validatePreset) params ["_preset"];
if (_preset isEqualTo []) exitWith {""};

private _classes = [_preset] call RACA_fnc_flattenPresetClasses;
if (_classes isEqualTo []) exitWith {""};

private _newline = toString [13, 10];
private _commentName = ((toArray (_preset select 2)) select {_x >= 32 && {_x isNotEqualTo 127}});
_commentName = toString _commentName;

private _lines = [
    "/*",
    " * Generated by Restricted Arsenal Creation Assistant.",
    format [" * Preset: %1", _commentName],
    " * Save this file as raca_arsenal.sqf in the mission folder.",
    ' * Call it from each Eden object Init field with:',
    ' * [this] execVM "raca_arsenal.sqf";',
    " * The same file may be called by any number of objects.",
    " */",
    "",
    'params [["_box", objNull, [objNull]]];',
    "if (isNull _box) exitWith {};",
    "if (!isServer) exitWith {};",
    "",
    "private _arsenalItems = ["
];

{
    private _suffix = [",", ""] select (_forEachIndex isEqualTo ((count _classes) - 1));
    _lines pushBack format ['    "%1"%2', _x, _suffix];
} forEach _classes;

_lines append [
    "];",
    "",
    "_arsenalItems = _arsenalItems arrayIntersect _arsenalItems;",
    "",
    "[_box, true] call ace_arsenal_fnc_removeBox;",
    "[_box, _arsenalItems, true] call ace_arsenal_fnc_initBox;"
];

_lines joinString _newline
