#define RACA_EDEN_GRID_W (pixelW * pixelGrid * 0.50)
#define RACA_EDEN_GRID_H (pixelH * pixelGrid * 0.50)
#define RACA_EDEN_IDC_PRESET 9101
#define RACA_EDEN_IDC_SUMMARY 9102
#define RACA_EDEN_IDD_CONFIG 905100
#define RACA_EDEN_IDC_SLOT_LIST 9200
#define RACA_EDEN_IDC_SLOT_NAME 9201
#define RACA_EDEN_IDC_SLOT_PRESET 9202
#define RACA_EDEN_IDC_SLOT_ENABLED 9203
#define RACA_EDEN_IDC_SLOT_HIDE_DENIED 9204
#define RACA_EDEN_IDC_SLOT_ICON 9205
#define RACA_EDEN_IDC_ACCESS_MODE 9206
#define RACA_EDEN_IDC_DENIAL_MESSAGE 9207
#define RACA_EDEN_IDC_CONDITION_LIST 9208
#define RACA_EDEN_IDC_CONDITION_KIND 9209
#define RACA_EDEN_IDC_CONDITION_VALUE 9210
#define RACA_EDEN_IDC_EDITOR_STATUS 9211
#define RACA_EDEN_IDC_DASHBOARD_LIST 9212
